Initial CI setup for Lighthouse

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -17,9 +17,13 @@ jobs:
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
-    - name: yarn install, build
+    - name: yarn install and build
       run: |
         yarn install
         yarn build --if-present
       env:
         CI: true
+    - name: Lighthouse
+      run: |
+        yarn add -g @lhci/cli
+        lhci autorun || echo "LHCI failed!"
